# --- Day 13: Point of Incidence ---
With your help, the hot springs team locates an appropriate spring which launches you neatly and precisely up to the edge of Lava Island.

There's just one problem: you don't see any lava.

You do see a lot of ash and igneous rock; there are even what look like gray mountains scattered around. After a while, you make your way to a nearby cluster of mountains only to discover that the valley between them is completely full of large mirrors. Most of the mirrors seem to be aligned in a consistent way; perhaps you should head in that direction?

As you move through the valley of mirrors, you find that several of them have fallen from the large metal frames keeping them in place. The mirrors are extremely flat and shiny, and many of the fallen mirrors have lodged into the ash at strange angles. Because the terrain is all one color, it's hard to tell where it's safe to walk or where you're about to run into a mirror.

You note down the patterns of ash (.) and rocks (#) that you see as you walk (your puzzle input); perhaps by carefully analyzing these patterns, you can figure out where the mirrors are!

For example:
```
#.##..##.
..#.##.#.
##......#
##......#
..#.##.#.
..##..##.
#.#.##.#.

#...##..#
#....#..#
..##..###
#####.##.
#####.##.
..##..###
#....#..#
```
To find the reflection in each pattern, you need to find a perfect reflection across either a horizontal line between two rows or across a vertical line between two columns.

In the first pattern, the reflection is across a vertical line between two columns; arrows on each of the two columns point at the line between the columns:
```
123456789
    ><   
#.##..##.
..#.##.#.
##......#
##......#
..#.##.#.
..##..##.
#.#.##.#.
    ><   
123456789
```
In this pattern, the line of reflection is the vertical line between columns 5 and 6. Because the vertical line is not perfectly in the middle of the pattern, part of the pattern (column 1) has nowhere to reflect onto and can be ignored; every other column has a reflected column within the pattern and must match exactly: column 2 matches column 9, column 3 matches 8, 4 matches 7, and 5 matches 6.

The second pattern reflects across a horizontal line instead:
```
1 #...##..# 1
2 #....#..# 2
3 ..##..### 3
4v#####.##.v4
5^#####.##.^5
6 ..##..### 6
7 #....#..# 7
```
This pattern reflects across the horizontal line between rows 4 and 5. Row 1 would reflect with a hypothetical row 8, but since that's not in the pattern, row 1 doesn't need to match anything. The remaining rows match: row 2 matches row 7, row 3 matches row 6, and row 4 matches row 5.

To summarize your pattern notes, add up the number of columns to the left of each vertical line of reflection; to that, also add 100 multiplied by the number of rows above each horizontal line of reflection. In the above example, the first pattern's vertical line has 5 columns to its left and the second pattern's horizontal line has 4 rows above it, a total of 405.

**Find the line of reflection in each of the patterns in your notes. What number do you get after summarizing all of your notes?**

In [1]:
from utilities import get_lines

In [2]:
import pandas as pd

In [62]:
lines=get_lines('input', day=13)

In [95]:
patterns = list()
pattern = list()
for line in lines:
    if line=='':
        patterns.append(pattern)
        pattern = list()
    else:
        pattern.append([ch for ch in line])
patterns.append(pattern)
patterns = [pd.DataFrame(pattern) for pattern in patterns]

In [96]:
patterns[0]

    0  1  2  3  4  5  6
0   #  #  .  #  .  .  #
1   #  #  #  .  .  .  .
2   #  .  .  #  #  #  #
3   .  #  #  #  #  #  #
4   #  .  #  #  .  .  #
5   #  #  #  .  .  .  .
6   #  #  .  .  #  #  .
7   .  .  #  #  #  #  #
8   #  #  .  #  #  #  #
9   #  #  #  #  .  .  #
10  #  .  #  #  #  #  #
11  #  .  #  #  #  #  #
12  #  #  #  #  .  .  #
13  #  #  .  #  #  #  #
14  .  .  #  #  #  #  #
15  #  #  .  .  #  #  .
16  #  #  .  .  .  .  .

In [97]:
def is_reflect(df, row1, row2):
    '''
    parameters:
    df: pd.DataFrame of pattern
    row1, row2: int, int index values of row of df to check for reflection
    '''
    if sum(df.loc[row1]!=df.loc[row2])==0:
        return True
    return False

In [98]:
def get_reflect_indexes(df):
    '''
    parameters:
    df: pd.DataFrame of pattern

    returns:
    i: int index i of row of df where reflection starts
    '''
    indexes = list()
    for i in range(df.shape[0]-1):
        if is_reflect(df, i, i+1):
            indexes.append(i)
    return indexes

In [99]:
reflect_index = get_reflect_indexes(patterns[2])
reflect_index

[4, 10]

In [126]:
def get_reflection_at_index(df, idx):
    i = idx-1
    j = idx+2
    while (i>=0)&(j<df.shape[0]):
        # print(i,j)
        if is_reflect(df, i, j):
            i-=1
            j+=1
        else:
            return -1
    return idx+1

In [127]:
def get_total_reflections(df):
    reflect_indexes = get_reflect_indexes(df)
    value = -1
    for idx in reflect_indexes:
        v = get_reflection_at_index(df, idx)
        if v > value:
            value = v
    return value

In [128]:
get_total_reflections(patterns[2])

11

In [129]:
def get_horizontal_value(df):
    return 100*get_total_reflections(df)

In [130]:
get_horizontal_value(patterns[0])

-100

In [131]:
def get_vertical_value(df):
    return get_total_reflections(df.T)

In [132]:
get_vertical_value(patterns[0])

5

In [133]:
total = 0
for pattern in patterns:
    vert = get_vertical_value(pattern)
    horiz = get_horizontal_value(pattern)
    if vert > 0:
        total += vert
    if horiz > 0:
        total += horiz
total

34889

In [79]:
pattern = patterns[2]
vert = get_vertical_value(pattern)
horiz = get_horizontal_value(pattern)
print(vert, horiz)

-1 -100

In [80]:
pattern

    0  1  2  3  4  5  6
0   .  #  .  .  #  .  #
1   #  .  #  #  .  .  #
2   #  #  .  .  .  .  .
3   .  .  .  .  #  #  .
4   .  .  .  .  .  #  .
5   .  .  .  .  .  #  .
6   .  .  .  .  #  #  .
7   #  #  .  .  .  .  .
8   #  #  #  #  .  .  #
9   .  #  .  .  #  .  #
10  #  #  #  .  #  #  .
11  #  #  #  .  #  #  .
12  .  #  .  .  #  .  #